version: "3.9"
services:
  influxdb:
    image: "influxdb:1.8"
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=false

    ports:
      - "127.0.0.1:8086:8086"
  arangodb:
    image: "arangodb"
    depends_on:
      - "influxdb"
    environment:
      - ARANGO_NO_AUTH=false
      - ARANGO_ROOT_PASSWORD=ROOT
    ports:
      - "127.0.0.1:8529:8529"

  loader:
    image: "co2at.loader"
    depends_on:
      - "arangodb"
    environment:
      - DOCKER_DB_INFLUX_ADDRESS=influxdb
      - DOCKER_DB_ARANGO_ADDRESS=arangodb
      - DOCKER_DB_INFLUX_PORT=8086
      - DOCKER_DB_ARANGO_PORT=8529
